/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */
import type { GetNotesParams, Note } from '../../../types/notes';

import { customInstance } from '../../../lib/api/client.ts';

/**
 * @summary Get all notes for a user
 */
export const getNotes = (params: GetNotesParams) => {
  return customInstance<Note[]>({ url: `/api/v1/notes`, method: 'GET', params });
};
/**
 * @summary Create a new note
 */
export const createNote = (note: Note) => {
  return customInstance<Note>({
    url: `/api/v1/notes`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: note,
  });
};
/**
 * @summary Get a note by ID
 */
export const getNoteById = (id: number) => {
  return customInstance<Note>({ url: `/api/v1/notes/${id}`, method: 'GET' });
};
/**
 * @summary Update a note's title and content
 */
export const updateNote = (id: number, note: Note) => {
  return customInstance<Note>({
    url: `/api/v1/notes/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: note,
  });
};
/**
 * @summary Delete a note by ID
 */
export const deleteNote = (id: number) => {
  return customInstance<void>({ url: `/api/v1/notes/${id}`, method: 'DELETE' });
};
export type GetNotesResult = NonNullable<Awaited<ReturnType<typeof getNotes>>>;
export type CreateNoteResult = NonNullable<Awaited<ReturnType<typeof createNote>>>;
export type GetNoteByIdResult = NonNullable<Awaited<ReturnType<typeof getNoteById>>>;
export type UpdateNoteResult = NonNullable<Awaited<ReturnType<typeof updateNote>>>;
export type DeleteNoteResult = NonNullable<Awaited<ReturnType<typeof deleteNote>>>;
