/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateNoteRequest,
  CreateNoteResponse,
  GetNoteResponse,
  ListNotesResponse,
  Note,
  UpdateNoteResponse
} from '../../../types/notes';

import { customInstance } from '../../../lib/api/client.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Get all notes for a user
 */
export const getNotes = (

 options?: SecondParameter<typeof customInstance<ListNotesResponse>>,) => {
      return customInstance<ListNotesResponse>(
      {url: `/api/v1/notes`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create a new note
 */
export const createNote = (
    createNoteRequest: CreateNoteRequest,
 options?: SecondParameter<typeof customInstance<CreateNoteResponse>>,) => {
      return customInstance<CreateNoteResponse>(
      {url: `/api/v1/notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNoteRequest
    },
      options);
    }
  /**
 * @summary Get a note by ID
 */
export const getNoteById = (
    id: number,
 options?: SecondParameter<typeof customInstance<GetNoteResponse>>,) => {
      return customInstance<GetNoteResponse>(
      {url: `/api/v1/notes/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Update a note's title and content
 */
export const updateNote = (
    id: number,
    note: Note,
 options?: SecondParameter<typeof customInstance<UpdateNoteResponse>>,) => {
      return customInstance<UpdateNoteResponse>(
      {url: `/api/v1/notes/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: note
    },
      options);
    }
  /**
 * @summary Delete a note by ID
 */
export const deleteNote = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/notes/${id}`, method: 'DELETE'
    },
      options);
    }
  export type GetNotesResult = NonNullable<Awaited<ReturnType<typeof getNotes>>>
export type CreateNoteResult = NonNullable<Awaited<ReturnType<typeof createNote>>>
export type GetNoteByIdResult = NonNullable<Awaited<ReturnType<typeof getNoteById>>>
export type UpdateNoteResult = NonNullable<Awaited<ReturnType<typeof updateNote>>>
export type DeleteNoteResult = NonNullable<Awaited<ReturnType<typeof deleteNote>>>
