spring.application.name=user-service

# Environment variable defaults
USER_SERVICE_APP_PORT=8001
USER_SERVICE_POSTGRES_URL=user-service-db
USER_SERVICE_POSTGRES_PORT_INT=5432
USER_SERVICE_POSTGRES_DB=public
USER_SERVICE_POSTGRES_USER=admin
USER_SERVICE_POSTGRES_PASSWORD=admin

server.port=${USER_SERVICE_APP_PORT}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${SERVICES_POSTGRES_URL}:${SERVICES_POSTGRES_PORT_INT}/user_service_db
spring.datasource.username=${SERVICES_POSTGRES_USER}
spring.datasource.password=${SERVICES_POSTGRES_PASSWORD}

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

management.endpoints.web.exposure.include=prometheus,health
management.prometheus.metrics.export.enabled=true