spring.application.name=user-service

# Environment variable defaults
USER_SERVICE_APP_PORT=8001

server.port=${USER_SERVICE_APP_PORT}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${SERVICES_POSTGRES_URL}:${SERVICES_POSTGRES_PORT_INT}/user_service_db
spring.datasource.username=${SERVICES_POSTGRES_USER}
spring.datasource.password=${SERVICES_POSTGRES_PASSWORD}

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

# JWT configuration
jwt.private-key=${JWT_PRIVATE_KEY:}
jwt.public-key=${JWT_PUBLIC_KEY:}
management.endpoints.web.exposure.include=prometheus,health
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.endpoint.health.show-details=when_authorized
