---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: team-devopss26-monitoring
spec:
  hard:
    requests.cpu: "667m"
    requests.memory: "1Gi"
    limits.cpu: "667m"
    limits.memory: "1Gi"
