/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */
import type { Note } from './note.ts';

export type CreateNoteRequest = Note & { [key: string]: unknown } & Required<Pick<Note & { [key: string]: unknown }, 'title' | 'content'>>;
