/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifiedTimestampedNote } from './identifiedTimestampedNote.ts';

export type CreateNoteResponse = IdentifiedTimestampedNote &
  Required<
    Pick<IdentifiedTimestampedNote, 'id' | 'title' | 'content' | 'createdAt' | 'lastUpdatedAt'>
  >;
