/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifiedNote } from './identifiedNote.ts';
import type { Timestamped } from './timestamped.ts';

export type IdentifiedTimestampedNote = Timestamped & IdentifiedNote & Required<Pick<Timestamped & IdentifiedNote, 'id' | 'title' | 'content' | 'id' | 'title' | 'content'>>;
