/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */
import type { Identifier } from './identifier.ts';
import type { Note } from './note.ts';

export type IdentifiedNote = Identifier &
  Note &
  Required<Pick<Identifier & Note, 'title' | 'content'>>;
