/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Note Service API
 * OpenAPI spec version: 1.0.0
 */

export interface Note {
  /**
   * @maxLength 255
   * @pattern .*\S.*
   */
  title?: string;
  content?: string;
  [key: string]: unknown;
}
