/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ChatRequestModel } from './chatRequestModel.ts';

export interface ChatRequest {
  message: string;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     * @nullable
     */
  conversation_id?: number | null;
  model?: ChatRequestModel;
}
