/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * OpenAPI spec version: 1.0.0
 */

export interface ChatResponse {
  response?: string;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  conversation_id?: number;
}
