/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * OpenAPI spec version: 1.0.0
 */

export type ChatRequestModel = typeof ChatRequestModel[keyof typeof ChatRequestModel];


export const ChatRequestModel = {
  gemini: 'gemini',
  'groq-llama': 'groq-llama',
  mistral: 'mistral',
  cohere: 'cohere',
} as const;
