/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ChatMessage } from './chatMessage.ts';

export interface Conversation {
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  id?: number;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  user_id?: number;
  /** @nullable */
  title?: string | null;
  created_at?: string;
  messages?: ChatMessage[];
}
