/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ChatMessage } from './chatMessage.ts';

export interface Conversation {
  id?: number;
  user_id?: number;
  title?: string;
  created_at?: string;
  messages?: ChatMessage[];
}
