repos:
  - repo: local
    hooks:
      - id: lint-openapi-specs
        name: Lint OpenAPI specs
        language: node
        entry: npx @redocly/cli lint
        args:
          - api/calendar-service.yaml
          - api/checklist-service.yaml
          - api/genai-service.yaml
          - api/note-service.yaml
          - api/openapi.yaml
          - api/user-service.yaml
        pass_filenames: false
        files: ^api/.*\.yaml$
