/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarEvent, GetEventsParams } from '../../../types/calendar';

import { customInstance } from '../../../lib/api/client.ts';

/**
 * @summary Get all calendar events for a user
 */
export const getEvents = (params: GetEventsParams) => {
  return customInstance<CalendarEvent[]>({ url: `/api/v1/events`, method: 'GET', params });
};
/**
 * @summary Create a new calendar event
 */
export const createEvent = (calendarEvent: CalendarEvent) => {
  return customInstance<CalendarEvent>({
    url: `/api/v1/events`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: calendarEvent,
  });
};
/**
 * @summary Get a calendar event by ID
 */
export const getEventById = (id: number) => {
  return customInstance<CalendarEvent>({ url: `/api/v1/events/${id}`, method: 'GET' });
};
/**
 * Updates title, description, startTime, endTime, and location
 * @summary Update a calendar event
 */
export const updateEvent = (id: number, calendarEvent: CalendarEvent) => {
  return customInstance<CalendarEvent>({
    url: `/api/v1/events/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: calendarEvent,
  });
};
/**
 * @summary Delete a calendar event by ID
 */
export const deleteEvent = (id: number) => {
  return customInstance<void>({ url: `/api/v1/events/${id}`, method: 'DELETE' });
};
export type GetEventsResult = NonNullable<Awaited<ReturnType<typeof getEvents>>>;
export type CreateEventResult = NonNullable<Awaited<ReturnType<typeof createEvent>>>;
export type GetEventByIdResult = NonNullable<Awaited<ReturnType<typeof getEventById>>>;
export type UpdateEventResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>;
export type DeleteEventResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>;
