/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CalendarEvent,
  CreateCalendarEventRequest,
  CreateCalendarEventResponse,
  GetCalendarEventResponse,
  ListCalendarEventResponse,
  UpdateCalendarEventResponse,
} from '../../../types/calendar';

import { customInstance } from '../../../lib/api/client.ts';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all calendar events for a user
 */
export const getEvents = (
  options?: SecondParameter<typeof customInstance<ListCalendarEventResponse>>,
) => {
  return customInstance<ListCalendarEventResponse>(
    { url: `/api/v1/events`, method: 'GET' },
    options,
  );
};
/**
 * @summary Create a new calendar event
 */
export const createEvent = (
  createCalendarEventRequest: CreateCalendarEventRequest,
  options?: SecondParameter<typeof customInstance<CreateCalendarEventResponse>>,
) => {
  return customInstance<CreateCalendarEventResponse>(
    {
      url: `/api/v1/events`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCalendarEventRequest,
    },
    options,
  );
};
/**
 * @summary Get a calendar event by ID
 */
export const getEventById = (
  id: number,
  options?: SecondParameter<typeof customInstance<GetCalendarEventResponse>>,
) => {
  return customInstance<GetCalendarEventResponse>(
    { url: `/api/v1/events/${id}`, method: 'GET' },
    options,
  );
};
/**
 * Updates title, description, startTime, endTime, and location
 * @summary Update a calendar event
 */
export const updateEvent = (
  id: number,
  calendarEvent: CalendarEvent,
  options?: SecondParameter<typeof customInstance<UpdateCalendarEventResponse>>,
) => {
  return customInstance<UpdateCalendarEventResponse>(
    {
      url: `/api/v1/events/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: calendarEvent,
    },
    options,
  );
};
/**
 * @summary Delete a calendar event by ID
 */
export const deleteEvent = (id: number, options?: SecondParameter<typeof customInstance<void>>) => {
  return customInstance<void>({ url: `/api/v1/events/${id}`, method: 'DELETE' }, options);
};
export type GetEventsResult = NonNullable<Awaited<ReturnType<typeof getEvents>>>;
export type CreateEventResult = NonNullable<Awaited<ReturnType<typeof createEvent>>>;
export type GetEventByIdResult = NonNullable<Awaited<ReturnType<typeof getEventById>>>;
export type UpdateEventResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>;
export type DeleteEventResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>;
