spring.application.name=checklist-service

# Environment variable defaults
CHECKLIST_SERVICE_APP_PORT=8003
CHECKLIST_SERVICE_POSTGRES_URL=checklist-service-db
CHECKLIST_SERVICE_POSTGRES_PORT_INT=5432
CHECKLIST_SERVICE_POSTGRES_DB=public
CHECKLIST_SERVICE_POSTGRES_USER=admin
CHECKLIST_SERVICE_POSTGRES_PASSWORD=admin

server.port=${CHECKLIST_SERVICE_APP_PORT}
server.servlet.context-path=/api/checklist

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${CHECKLIST_SERVICE_POSTGRES_URL}:${CHECKLIST_SERVICE_POSTGRES_PORT_INT}/${CHECKLIST_SERVICE_POSTGRES_DB}
spring.datasource.username=${CHECKLIST_SERVICE_POSTGRES_USER}
spring.datasource.password=${CHECKLIST_SERVICE_POSTGRES_PASSWORD}

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized