spring.application.name=checklist-service
server.port=${CHECKLIST_SERVICE_APP_PORT}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${SERVICES_POSTGRES_URL}:${SERVICES_POSTGRES_PORT_INT}/checklist_service_db
spring.datasource.username=${SERVICES_POSTGRES_USER}
spring.datasource.password=${SERVICES_POSTGRES_PASSWORD}

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

management.endpoints.web.exposure.include=prometheus,health
management.prometheus.metrics.export.enabled=true