/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * OpenAPI spec version: 1.0.0
 */

export interface CalendarEvent {
  /**
     * @maxLength 255
     * @pattern .*\S.*
     */
  title?: string;
  description?: string;
  startTime?: string;
  endTime?: string;
  location?: string;
  [key: string]: unknown;
 }
