/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarEvent } from './calendarEvent.ts';

export type CreateCalendarEventRequest = CalendarEvent & { [key: string]: unknown } & Required<
    Pick<CalendarEvent & { [key: string]: unknown }, 'title' | 'startTime' | 'endTime'>
  >;
