/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifiedCalendarEvent } from './identifiedCalendarEvent.ts';

export type GetCalendarEventResponse = IdentifiedCalendarEvent & { [key: string]: unknown } & Required<Pick<IdentifiedCalendarEvent & { [key: string]: unknown }, 'title' | 'startTime' | 'endTime'>>;
