/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Calendar Service API
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarEvent } from './calendarEvent.ts';
import type { Identifier } from './identifier.ts';

export type IdentifiedCalendarEvent = Identifier & CalendarEvent;
