/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Identifier: {
            /** Format: int64 */
            id: number;
        } & {
            [key: string]: unknown;
        };
        Timestamped: {
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUpdatedAt: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: {
        id: components["schemas"]["Identifier"]["id"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
