apiVersion: v1
kind: Secret
metadata:
  name: genai-service-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  GEMINI_API_KEY: "{{ .Values.genaiService.geminiApiKey }}"
  SERVICES_POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
