{{- $pg := .Values.postgres }}
{{- range $name, $cfg := .Values.services }}
{{- $prefix := replace "-" "_" $name | upper }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ $.Values.global.namespace }}
type: Opaque
stringData:
  SERVICES_POSTGRES_PASSWORD: {{ $pg.password | quote }}
{{- end }}