/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * GenAI Service API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChatRequest,
  ChatResponse,
  Conversation,
  ConversationCreateRequest,
  DeleteConversation200,
  Health200,
} from '../../../types/genai';

import { customInstance } from '../../../lib/api/client.ts';

/**
 * @summary Health check
 */
export const health = () => {
  return customInstance<Health200>({ url: `/api/v1/health`, method: 'GET' });
};
/**
 * @summary Create a new chat conversation
 */
export const createConversation = (conversationCreateRequest: ConversationCreateRequest) => {
  return customInstance<Conversation>({
    url: `/api/v1/conversations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: conversationCreateRequest,
  });
};
/**
 * @summary Get a conversation by ID including all messages
 */
export const getConversation = (conversationId: number) => {
  return customInstance<Conversation>({
    url: `/api/v1/conversations/${conversationId}`,
    method: 'GET',
  });
};
/**
 * @summary Delete a conversation by ID
 */
export const deleteConversation = (conversationId: number) => {
  return customInstance<DeleteConversation200>({
    url: `/api/v1/conversations/${conversationId}`,
    method: 'DELETE',
  });
};
/**
 * @summary Send a message and get an AI response
 */
export const chat = (chatRequest: ChatRequest) => {
  return customInstance<ChatResponse>({
    url: `/api/v1/chat`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: chatRequest,
  });
};
export type HealthResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type CreateConversationResult = NonNullable<Awaited<ReturnType<typeof createConversation>>>;
export type GetConversationResult = NonNullable<Awaited<ReturnType<typeof getConversation>>>;
export type DeleteConversationResult = NonNullable<Awaited<ReturnType<typeof deleteConversation>>>;
export type ChatResult = NonNullable<Awaited<ReturnType<typeof chat>>>;
