spring.application.name=calendar-service

# Environment variable defaults
CALENDAR_SERVICE_APP_PORT=8004
CALENDAR_SERVICE_POSTGRES_URL=calendar-service-db
CALENDAR_SERVICE_POSTGRES_PORT_INT=5432
CALENDAR_SERVICE_POSTGRES_DB=public
CALENDAR_SERVICE_POSTGRES_USER=admin
CALENDAR_SERVICE_POSTGRES_PASSWORD=admin

server.port=${CALENDAR_SERVICE_APP_PORT}
server.servlet.context-path=/api/calendar

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${CALENDAR_SERVICE_POSTGRES_URL}:${CALENDAR_SERVICE_POSTGRES_PORT_INT}/${CALENDAR_SERVICE_POSTGRES_DB}
spring.datasource.username=${CALENDAR_SERVICE_POSTGRES_USER}
spring.datasource.password=${CALENDAR_SERVICE_POSTGRES_PASSWORD}

spring.liquibase.change-log=db/changelog/db.changelog-master.xml

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always