spring.application.name=note-service

# Environment variable defaults
NOTE_SERVICE_APP_PORT=8005
NOTE_SERVICE_POSTGRES_URL=note-service-db
NOTE_SERVICE_POSTGRES_PORT_INT=5432
NOTE_SERVICE_POSTGRES_DB=public
NOTE_SERVICE_POSTGRES_USER=admin
NOTE_SERVICE_POSTGRES_PASSWORD=admin

server.port=${NOTE_SERVICE_APP_PORT}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${NOTE_SERVICE_POSTGRES_URL}:${NOTE_SERVICE_POSTGRES_PORT_INT}/${NOTE_SERVICE_POSTGRES_DB}
spring.datasource.username=${NOTE_SERVICE_POSTGRES_USER}
spring.datasource.password=${NOTE_SERVICE_POSTGRES_PASSWORD}

spring.liquibase.change-log=db/changelog/db.changelog-master.xml