apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.global.namespace }}
  labels:
    app: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.port }}
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddyfile
          configMap:
            name: client-caddyfile