apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: {{ .Values.global.namespace }}
  labels:
    app: client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: client