/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * User Service API
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse, RegisterUserRequest } from '../../../types/users';

import { customInstance } from '../../../lib/api/client.ts';

/**
 * @summary Register a new user
 */
export const registerUser = (registerUserRequest: RegisterUserRequest) => {
  return customInstance<void>({
    url: `/api/v1/users/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerUserRequest,
  });
};
/**
 * @summary Login to get a JWT token using Basic Auth
 */
export const loginUser = () => {
  return customInstance<LoginResponse>({ url: `/api/v1/users/auth/login`, method: 'POST' });
};
/**
 * @summary Check for the validity of a JWT
 */
export const checkToken = () => {
  return customInstance<void>({ url: `/api/v1/users/auth/check-token`, method: 'GET' });
};
export type RegisterUserResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>;
export type LoginUserResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>;
export type CheckTokenResult = NonNullable<Awaited<ReturnType<typeof checkToken>>>;
