@startuml
!pragma layout smetana
'https://plantuml.com/use-case-diagram

title Use Case Diagram (Functional Requirements)

skinparam nodesep 60
skinparam ranksep 80
skinparam shadowing false

actor User

package "AI-integrated Life Management App" as system {
	package "User Account" as UserAccount {
		(Register User)
		(Log In)
	}

	package Chatbot as Chatbot {
		(Query the Chatbot)
		(Create Chat Conversation)
		(View Chat History)
		(Delete Chat Conversation)
	}

	package Notes as Notes {
		(Create Note)
		(Edit Note)
		(View Note)
		(Delete Note)
	}
	
	package Calendar as Calendar {
		(Create Event)
		(Edit Event)
		(View Event)
		(Delete Event)
	}
	
	package Checklists as Checklists {
		(Create Checklist)
		(Edit Checklist)
		(View Checklist)
		(Delete Checklist)
		(Manage Items in Checklist)
	}
}

User --> UserAccount
User --> Notes
User --> Calendar
User --> Checklists
User --> Chatbot
@enduml