openapi: 3.0.3
info:
  title: Note Service API
  version: 1.0.0

tags:
  - name: Notes
    description: Operations for managing notes

servers:
  - url: /

paths:
  /api/v1/notes:
    get:
      tags: [Notes]
      summary: Get all notes for a user
      operationId: getNotes
      security:
        - JWTAuth: []
      responses:
        '200':
          description: List of notes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNotesResponse'
        '401':
          description: Token either does not exist or is already expired
        '500':
          description: Unhandled error occurred

    post:
      tags: [Notes]
      summary: Create a new note
      operationId: createNote
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNoteRequest'
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateNoteResponse'
        '401':
          description: Token either does not exist or is already expired
        '500':
          description: Unhandled error occurred

  /api/v1/notes/{id}:
    get:
      tags: [Notes]
      summary: Get a note by ID
      operationId: getNoteById
      security:
        - JWTAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: The note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNoteResponse'
        '401':
          description: Token either does not exist or is already expired
        '403':
          description: Accessing note of someone else
        '404':
          description: Note not found
        '500':
          description: Unhandled error occurred

    put:
      tags: [Notes]
      summary: Update a note's title and content
      operationId: updateNote
      security:
        - JWTAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Updated note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateNoteResponse'
        '401':
          description: Token either does not exist or is already expired
        '403':
          description: Accessing note of someone else
        '404':
          description: Note not found
        '500':
          description: Unhandled error occurred

    delete:
      tags: [Notes]
      summary: Delete a note by ID
      operationId: deleteNote
      security:
        - JWTAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Note deleted
        '401':
          description: Token either does not exist or is already expired
        '403':
          description: Accessing note of someone else
        '404':
          description: Note not found
        '500':
          description: Unhandled error occurred

components:
  securitySchemes:
    JWTAuth:
      $ref: './common.yaml#/components/securitySchemes/JWTAuth'
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64

  schemas:
    Note:
      type: object
      additionalProperties: true
      properties:
        title:
          type: string
          pattern: '.*\S.*'
          maxLength: 255
          example: "Grocery List"
        content:
          type: string
          example: "Milk, Bread, Eggs, Apples"
    ListNotesResponse:
      type: object
      properties:
        notes:
          type: array
          items:
            $ref: "#/components/schemas/IdentifiedTimestampedNote"
      required:
        - notes
    CreateNoteRequest:
      allOf:
        - $ref: '#/components/schemas/Note'
        - type: object
          required:
            - title
            - content
    CreateNoteResponse:
      allOf:
        - $ref: '#/components/schemas/IdentifiedTimestampedNote'
    GetNoteResponse:
      allOf:
        - $ref: "#/components/schemas/IdentifiedTimestampedNote"
    UpdateNoteResponse:
      allOf:
        - $ref: "#/components/schemas/IdentifiedTimestampedNote"
    IdentifiedNote:
      type: object
      allOf:
        - $ref: './common.yaml#/components/schemas/Identifier'
        - $ref: "#/components/schemas/Note"
      required:
        - id
        - title
        - content
    IdentifiedTimestampedNote:
      type: object
      allOf:
        - $ref: './common.yaml#/components/schemas/Timestamped'
        - $ref: "#/components/schemas/IdentifiedNote"
      required:
        - id
        - title
        - content
        - createdAt
        - lastUpdatedAt
