openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
tags:
  - name: UserAuthentication
    description: Endpoints to manage user creation and authentication
servers:
  - url: /
paths:
  /api/v1/users/auth/register:
    post:
      tags:
        - UserAuthentication
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
      responses:
        '201':
          description: User created
        '409':
          description: User already exists
        '500':
          description: Unhandled error occurred
  /api/v1/users/auth/login:
    post:
      tags:
        - UserAuthentication
      summary: Login to get a JWT token using Basic Auth
      operationId: loginUser
      security:
        - BasicAuth: []
      responses:
        '200':
          description: Successfully authenticated, returns token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '401':
          description: Unable to authorize using given data
        '500':
          description: Unhandled error occurred
  /api/v1/users/auth/check-token:
    get:
      tags:
        - UserAuthentication
      summary: Check for the validity of a JWT
      operationId: checkToken
      responses:
        '200':
          description: Token exists and is not expired
        '401':
          description: Token either does not exist or is already expired
        '500':
          description: Unhandled error occurred
  /api/v1/users/auth/public-key:
    get:
      tags:
        - UserAuthentication
      summary: Provides other services with public key for JWT validation
      operationId: publicKey
      responses:
        '200':
          description: Returns the base64-encoded public key used for JWT validation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublicKeyResponse"
        '500':
          description: Unhandled error occurred

components:
  securitySchemes:
    BasicAuth:
      $ref: './common.yaml#/components/securitySchemes/BasicAuth'
  schemas:
    RegisterUserRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    PublicKeyResponse:
      type: object
      properties:
        publicKey:
          type: string