openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
tags:
  - name: UserAuthentication
    description: Endpoints to manage user creation and authentication
servers:
  - url: /
paths:
  /api/v1/users/auth/register:
    post:
      tags:
        - UserAuthentication
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
      responses:
        '201':
          description: User created
        '409':
          description: User already exists
        '500':
          description: Unhandled error occured
components:
  schemas:
    RegisterUserRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string