/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddChecklistItemRequest,
  AddChecklistItemResponse,
  ChecklistItem,
  CreateChecklistRequest,
  CreateChecklistResponse,
  GetChecklistResponse,
  GetChecklistsResponse,
  UpdateChecklistItemResponse,
  UpdateChecklistRequest,
  UpdateChecklistResponse
} from '../../../types/checklist';

import { customInstance } from '../../../lib/api/client.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Get all checklists for the authenticated user
 */
export const getChecklists = (

 options?: SecondParameter<typeof customInstance<GetChecklistsResponse>>,) => {
      return customInstance<GetChecklistsResponse>(
      {url: `/api/v1/checklists`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create a new checklist
 */
export const createChecklist = (
    createChecklistRequest: CreateChecklistRequest,
 options?: SecondParameter<typeof customInstance<CreateChecklistResponse>>,) => {
      return customInstance<CreateChecklistResponse>(
      {url: `/api/v1/checklists`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createChecklistRequest
    },
      options);
    }
  /**
 * @summary Get a checklist by ID including its items
 */
export const getChecklistById = (
    id: number,
 options?: SecondParameter<typeof customInstance<GetChecklistResponse>>,) => {
      return customInstance<GetChecklistResponse>(
      {url: `/api/v1/checklists/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Update a checklist's title
 */
export const updateChecklist = (
    id: number,
    updateChecklistRequest: UpdateChecklistRequest,
 options?: SecondParameter<typeof customInstance<UpdateChecklistResponse>>,) => {
      return customInstance<UpdateChecklistResponse>(
      {url: `/api/v1/checklists/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateChecklistRequest
    },
      options);
    }
  /**
 * @summary Delete a checklist by ID
 */
export const deleteChecklist = (
    id: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/checklists/${id}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary Add an item to a checklist
 */
export const addChecklistItem = (
    id: number,
    addChecklistItemRequest: AddChecklistItemRequest,
 options?: SecondParameter<typeof customInstance<AddChecklistItemResponse>>,) => {
      return customInstance<AddChecklistItemResponse>(
      {url: `/api/v1/checklists/${id}/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addChecklistItemRequest
    },
      options);
    }
  /**
 * Can be used to change the text, toggle completed, or reorder
 * @summary Update a checklist item
 */
export const updateChecklistItem = (
    id: number,
    itemId: number,
    checklistItem: ChecklistItem,
 options?: SecondParameter<typeof customInstance<UpdateChecklistItemResponse>>,) => {
      return customInstance<UpdateChecklistItemResponse>(
      {url: `/api/v1/checklists/${id}/items/${itemId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: checklistItem
    },
      options);
    }
  /**
 * @summary Remove an item from a checklist
 */
export const deleteChecklistItem = (
    id: number,
    itemId: number,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/checklists/${id}/items/${itemId}`, method: 'DELETE'
    },
      options);
    }
  export type GetChecklistsResult = NonNullable<Awaited<ReturnType<typeof getChecklists>>>
export type CreateChecklistResult = NonNullable<Awaited<ReturnType<typeof createChecklist>>>
export type GetChecklistByIdResult = NonNullable<Awaited<ReturnType<typeof getChecklistById>>>
export type UpdateChecklistResult = NonNullable<Awaited<ReturnType<typeof updateChecklist>>>
export type DeleteChecklistResult = NonNullable<Awaited<ReturnType<typeof deleteChecklist>>>
export type AddChecklistItemResult = NonNullable<Awaited<ReturnType<typeof addChecklistItem>>>
export type UpdateChecklistItemResult = NonNullable<Awaited<ReturnType<typeof updateChecklistItem>>>
export type DeleteChecklistItemResult = NonNullable<Awaited<ReturnType<typeof deleteChecklistItem>>>
