/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ChecklistItem } from './checklistItem.ts';

export type AddChecklistItemRequest = ChecklistItem & { [key: string]: unknown } & Required<
    Pick<ChecklistItem & { [key: string]: unknown }, 'text'>
  >;
