/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */

export interface ChecklistItem {
  /** @maxLength 1000 */
  text?: string;
  completed?: boolean;
  position?: number;
  [key: string]: unknown;
}
