/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ChecklistItem } from './checklistItem.ts';

export interface Checklist {
  id?: number;
  userId?: number;
  title?: string;
  createdAt?: string;
  items?: ChecklistItem[];
}
