/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifiedChecklistItem } from './identifiedChecklistItem.ts';

export interface Checklist {
  /**
   * @maxLength 255
   * @pattern .*\S.*
   */
  title?: string;
  createdAt?: string;
  items?: IdentifiedChecklistItem[];
  [key: string]: unknown;
}
