/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifiedChecklist } from './identifiedChecklist.ts';

export type GetChecklistResponse = IdentifiedChecklist & { [key: string]: unknown } & Required<Pick<IdentifiedChecklist & { [key: string]: unknown }, 'title'>>;
