/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ChecklistItem } from './checklistItem.ts';
import type { Identifier } from './identifier.ts';

export type IdentifiedChecklistItem = Identifier & ChecklistItem;
