/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifiedChecklistItem } from './identifiedChecklistItem.ts';

export type UpdateChecklistItemResponse = IdentifiedChecklistItem & {
  [key: string]: unknown;
} & Required<Pick<IdentifiedChecklistItem & { [key: string]: unknown }, 'text'>>;
