/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Checklist Service API
 * OpenAPI spec version: 1.0.0
 */
import type { Checklist } from './checklist.ts';

export type UpdateChecklistRequest = Checklist & { [key: string]: unknown } & Required<
    Pick<Checklist & { [key: string]: unknown }, 'title'>
  >;
